nome = str(input('Digite seu nome: ')).strip()
maiuscula = nome.upper()
minuscula = nome.lower()
total = len(nome)- nome.count(' ')
firstname = nome.find(' ')
print('Nome completo:{} '.format(nome))
print('seu nome em maisuculo {} '.format(maiuscula))
print('seu nome em minuscula {} '.format(minuscula))
print('total de letras no seu nome completo: {}'.format(total))
print('primeiro nome: {}'.format(firstname))